### PR TITLE
Add vdom provider parameter

### PR DESCRIPTION
**Pull request by tmarshall98**
Add support for the new Client.VDom field from https://github.com/Ouest-France/gofortiadc/pull/15

For use in the terraform provider: https://github.com/Ouest-France/terraform-provider-fortiadc

### CODE REVIEW

**Comment by tmarshall98** [comment]
No worries @pablo-ruth, I'm using my changes internally through a custom build, just want to contribute them back upstream in case anyone else needs it!

**Comment by pablo-ruth** [comment]
Hi @tmarshall98,
I'm back to work, I merged your PR in gofortiadc library https://github.com/Ouest-France/gofortiadc/pull/15 and released [v0.2.1](https://github.com/Ouest-France/gofortiadc/releases/tag/v0.2.1). I reviewed and tested this PR too, and LGTM. So I just let you update the dependency on this PR and I'll merge it! Thanks

**Comment by pablo-ruth** [comment]
Oh and please add the new parameter to the doc too: https://github.com/Ouest-France/terraform-provider-fortiadc/blob/master/docs/index.md :)

**Comment by tmarshall98** [comment]
Thanks. Let me know if there are any other changes necessary.

**Comment by pablo-ruth** [comment]
Perfect, it's merged. Thanks for your contribution!

**Pull request merged**
